### ISSUE TITLE
Unraid 6.9.0-rc2 Coral Plugin App Not Working

### ISSUE THREAD

**Issue by mitchross** [ich777/unraid-coral-driver#1]
Have a dual edge tpu m2 card. 
Installed the Coral  Driver App from Community Plugins for 6.9 RC2. Rebooted.

```
root@Tower:~# lsmod | grep apex
apex                   16384  0
gasket                 90112  1 apex
root@Tower:~# lspci -nn | grep 089a
01:00.0 System peripheral [0880]: Global Unichip Corp. Coral Edge TPU [1ac1:089a]
root@Tower:~# ls /dev/apex_0
/dev/apex_0
root@Tower:~# 

```

1. Run Frigate, notice Logs. 

```
Starting migrations
peewee_migrate INFO : Starting migrations
There is nothing to migrate
peewee_migrate INFO : There is nothing to migrate
frigate.mqtt INFO : MQTT connected
detector.coral INFO : Starting detection process: 50
frigate.edgetpu INFO : Attempting to load TPU as usb
Process detector:coral:
frigate.edgetpu INFO : No EdgeTPU detected.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 152, in load_delegate
delegate = Delegate(library, options)
File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 111, in __init__
raise ValueError(capture.message)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
self._target(*self._args, **self._kwargs)
File "/opt/frigate/frigate/edgetpu.py", line 124, in run_detector
object_detector = LocalObjectDetector(tf_device=tf_device, num_threads=num_threads)
File "/opt/frigate/frigate/edgetpu.py", line 63, in __init__
edge_tpu_delegate = load_delegate('libedgetpu.so.1.0', device_config)
File "/usr/local/lib/python3.8/dist-packages/tflite_runtime/interpreter.py", line 154, in load_delegate
```

**Comment by mitchross** [comment]
Nvm you must pass this if you use PCI in frigate, USB is already default... 

detectors:
  coral_pci:
      type: edgetpu
      device: pci
